//! # gRPC Server Implementation
//!
//! Exposes a high-performance binary protocol for T-VectorDB.

use std::sync::Arc;
use tonic::{Request, Response, Status};

use crate::api_server::AppState;
use crate::execution_engine::{batch_search, hybrid_search, search_ram_store_with_options};

// Import code generated by tonic-build from proto/tvectordb.proto
pub mod pb {
    tonic::include_proto!("tvectordb");
}

use pb::t_vector_server::TVector;
use pb::{
    BatchInsertRequest, BatchInsertResponse, BatchSearchRequest, BatchSearchResponse,
    DeleteRequest, DeleteResponse, InsertRequest, InsertResponse, SearchRequest,
    SearchResponse, SearchResult,
};

pub struct TVectorService {
    pub state: Arc<AppState>,
}

#[tonic::async_trait]
impl TVector for TVectorService {
    async fn insert(
        &self,
        request: Request<InsertRequest>,
    ) -> Result<Response<InsertResponse>, Status> {
        let req = request.into_inner();
        let vector = req.vector.ok_or_else(|| Status::invalid_argument("Missing vector"))?;

        if vector.values.len() != self.state.index.d {
            return Err(Status::invalid_argument(format!(
                "Dimension mismatch: expected {}, got {}",
                self.state.index.d,
                vector.values.len()
            )));
        }

        let meta_opt = if vector.metadata.is_empty() { None } else { Some(&vector.metadata) };

        match self.state.db.insert(&self.state.index, &vector.values, vector.id, meta_opt) {
            Ok(()) => Ok(Response::new(InsertResponse {
                success: true,
                message: "Inserted successfully".into(),
                id: vector.id,
            })),
            Err(e) => Err(Status::internal(format!("Database error: {}", e))),
        }
    }

    async fn insert_batch(
        &self,
        request: Request<BatchInsertRequest>,
    ) -> Result<Response<BatchInsertResponse>, Status> {
        let req = request.into_inner();
        
        let mut pairs = Vec::with_capacity(req.vectors.len());
        for v in req.vectors {
            let meta = if v.metadata.is_empty() { None } else { Some(v.metadata) };
            if v.values.len() != self.state.index.d {
                return Err(Status::invalid_argument(format!(
                    "Vector {} dimension mismatch: expected {}, got {}",
                    v.id, self.state.index.d, v.values.len()
                )));
            }
            pairs.push((v.id, v.values, meta));
        }

        match self.state.db.insert_batch(&self.state.index, &pairs) {
            Ok(count) => Ok(Response::new(BatchInsertResponse {
                success: true,
                inserted: count as u32,
                total_vectors: self.state.db.len() as u32,
            })),
            Err(e) => Err(Status::internal(format!("Batch insert error: {}", e))),
        }
    }

    async fn search(
        &self,
        request: Request<SearchRequest>,
    ) -> Result<Response<SearchResponse>, Status> {
        let req = request.into_inner();

        if req.query.len() != self.state.index.d {
            return Err(Status::invalid_argument(format!(
                "Dimension mismatch: expected {}, got {}",
                self.state.index.d,
                req.query.len()
            )));
        }

        if self.state.db.is_empty() {
            return Ok(Response::new(SearchResponse {
                results: vec![],
                total_vectors: 0,
                mode: "empty".into(),
            }));
        }

        let top_k = if req.top_k == 0 { 5 } else { req.top_k as usize };
        let ef = if req.ef_search == 0 { 100 } else { req.ef_search as usize };

        let valid_ids = self.state.db.get_filtered_ids(&req.filter);

        let (results, mode) = if req.exact {
            (
                hybrid_search(&self.state.db, &self.state.index, &req.query, top_k, valid_ids.as_ref()),
                "exact (hybrid)",
            )
        } else {
            let graph = self.state.db.hnsw.read().unwrap();
            if graph.is_empty() {
                let ram_guard = self.state.db.ram.read().unwrap();
                let res = search_ram_store_with_options(
                    &self.state.index,
                    &ram_guard,
                    &req.query,
                    top_k,
                    false, // Disable QJL to prevent noise
                    valid_ids.as_ref(),
                );
                (res, "approximate (linear)")
            } else {
                let ram_guard = self.state.db.ram.read().unwrap();
                let res = graph.search(&req.query, &self.state.index, &ram_guard, top_k, ef, valid_ids.as_ref());
                (res, "approximate (hnsw)")
            }
        };

        let grpc_results = results
            .into_iter()
            .map(|(id, score)| SearchResult { id, score })
            .collect();

        Ok(Response::new(SearchResponse {
            results: grpc_results,
            total_vectors: self.state.db.len() as u32,
            mode: mode.to_string(),
        }))
    }

    async fn search_batch(
        &self,
        request: Request<BatchSearchRequest>,
    ) -> Result<Response<BatchSearchResponse>, Status> {
        let req = request.into_inner();
        let top_k = if req.top_k == 0 { 5 } else { req.top_k as usize };

        let mut queries = Vec::with_capacity(req.queries.len());
        for (i, q) in req.queries.into_iter().enumerate() {
            if q.values.len() != self.state.index.d {
                return Err(Status::invalid_argument(format!(
                    "Query {} dimension mismatch: expected {}, got {}",
                    i,
                    self.state.index.d,
                    q.values.len()
                )));
            }
            queries.push(q.values);
        }

        let ram_guard = self.state.db.ram.read().unwrap();
        // gRPC batch search doesn't accept a global filter yet
        let all_results = batch_search(&self.state.index, &ram_guard, &queries, top_k, None);
        drop(ram_guard);

        let batch_responses = all_results
            .into_iter()
            .map(|results| {
                let grpc_results = results
                    .into_iter()
                    .map(|(id, score)| SearchResult { id, score })
                    .collect();
                SearchResponse {
                    results: grpc_results,
                    total_vectors: self.state.db.len() as u32,
                    mode: "approximate (batch)".into(),
                }
            })
            .collect();

        Ok(Response::new(BatchSearchResponse {
            batch_results: batch_responses,
            total_vectors: self.state.db.len() as u32,
        }))
    }

    async fn delete(
        &self,
        request: Request<DeleteRequest>,
    ) -> Result<Response<DeleteResponse>, Status> {
        let req = request.into_inner();
        match self.state.db.delete(req.id) {
            Ok(deleted) => Ok(Response::new(DeleteResponse {
                success: true,
                deleted,
                id: req.id,
            })),
            Err(e) => Err(Status::internal(format!("Delete error: {}", e))),
        }
    }
}
