# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tvectordb_pb2 as tvectordb__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tvectordb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TVectorStub(object):
    """The core service exposing T-VectorDB methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/tvectordb.TVector/Insert',
                request_serializer=tvectordb__pb2.InsertRequest.SerializeToString,
                response_deserializer=tvectordb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.InsertBatch = channel.unary_unary(
                '/tvectordb.TVector/InsertBatch',
                request_serializer=tvectordb__pb2.BatchInsertRequest.SerializeToString,
                response_deserializer=tvectordb__pb2.BatchInsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/tvectordb.TVector/Search',
                request_serializer=tvectordb__pb2.SearchRequest.SerializeToString,
                response_deserializer=tvectordb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchBatch = channel.unary_unary(
                '/tvectordb.TVector/SearchBatch',
                request_serializer=tvectordb__pb2.BatchSearchRequest.SerializeToString,
                response_deserializer=tvectordb__pb2.BatchSearchResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/tvectordb.TVector/Delete',
                request_serializer=tvectordb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=tvectordb__pb2.DeleteResponse.FromString,
                _registered_method=True)


class TVectorServicer(object):
    """The core service exposing T-VectorDB methods
    """

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TVectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=tvectordb__pb2.InsertRequest.FromString,
                    response_serializer=tvectordb__pb2.InsertResponse.SerializeToString,
            ),
            'InsertBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertBatch,
                    request_deserializer=tvectordb__pb2.BatchInsertRequest.FromString,
                    response_serializer=tvectordb__pb2.BatchInsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=tvectordb__pb2.SearchRequest.FromString,
                    response_serializer=tvectordb__pb2.SearchResponse.SerializeToString,
            ),
            'SearchBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBatch,
                    request_deserializer=tvectordb__pb2.BatchSearchRequest.FromString,
                    response_serializer=tvectordb__pb2.BatchSearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=tvectordb__pb2.DeleteRequest.FromString,
                    response_serializer=tvectordb__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tvectordb.TVector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tvectordb.TVector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TVector(object):
    """The core service exposing T-VectorDB methods
    """

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tvectordb.TVector/Insert',
            tvectordb__pb2.InsertRequest.SerializeToString,
            tvectordb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tvectordb.TVector/InsertBatch',
            tvectordb__pb2.BatchInsertRequest.SerializeToString,
            tvectordb__pb2.BatchInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tvectordb.TVector/Search',
            tvectordb__pb2.SearchRequest.SerializeToString,
            tvectordb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tvectordb.TVector/SearchBatch',
            tvectordb__pb2.BatchSearchRequest.SerializeToString,
            tvectordb__pb2.BatchSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tvectordb.TVector/Delete',
            tvectordb__pb2.DeleteRequest.SerializeToString,
            tvectordb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
